"""
Django settings for django_authentication project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import socket
if socket.gethostname()=="DESKTOP-4QDSNTL":
    from .local_settings import *
else:
    from .production_settings import *